services:
  backend: 
    build: 
      context: .
    container_name: backend-container
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=naruto92
    ports:
      - 8080:8080
  db:
    image: "postgres"
    container_name: postgres-container
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_PASSWORD=naruto92"
      - "POSTGRES_USER=postgres"