--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

-- Started on 2025-03-28 16:30:17

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 57994)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

-- *not* creating schema, since initdb creates it

CREATE SCHEMA IF NOT EXISTS public;

ALTER SCHEMA public OWNER TO postgres;

--
-- TOC entry 4875 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 57995)
-- Name: activation_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.activation_token (
    id uuid NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    token character varying(255) NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.activation_token OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 58001)
-- Name: event; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.event (
    id bigint NOT NULL,
    capacity bigint,
    created_date timestamp(6) without time zone,
    date_event timestamp(6) without time zone,
    description character varying(255),
    image bytea,
    local_event character varying(255),
    title character varying(255),
    created_by uuid NOT NULL
);


ALTER TABLE public.event OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 58000)
-- Name: event_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 58009)
-- Name: events_registrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.events_registrations (
    id bigint NOT NULL,
    registration_date timestamp(6) without time zone NOT NULL,
    event_id bigint NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.events_registrations OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 58008)
-- Name: events_registrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.events_registrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_registrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 58014)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id uuid NOT NULL,
    active boolean,
    email character varying(255),
    name character varying(255),
    password character varying(255),
    role smallint,
    CONSTRAINT users_role_check CHECK (((role >= 0) AND (role <= 1)))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 4710 (class 2606 OID 57999)
-- Name: activation_token activation_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activation_token
    ADD CONSTRAINT activation_token_pkey PRIMARY KEY (id);


--
-- TOC entry 4716 (class 2606 OID 58007)
-- Name: event event_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event
    ADD CONSTRAINT event_pkey PRIMARY KEY (id);


--
-- TOC entry 4718 (class 2606 OID 58013)
-- Name: events_registrations events_registrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events_registrations
    ADD CONSTRAINT events_registrations_pkey PRIMARY KEY (id);


--
-- TOC entry 4712 (class 2606 OID 58025)
-- Name: activation_token ukehvrv4ecsqib45ub95pdi21o5; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activation_token
    ADD CONSTRAINT ukehvrv4ecsqib45ub95pdi21o5 UNIQUE (user_id);


--
-- TOC entry 4714 (class 2606 OID 58023)
-- Name: activation_token ukhqvnsd04g5ca3tybwwtcjjc7s; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activation_token
    ADD CONSTRAINT ukhqvnsd04g5ca3tybwwtcjjc7s UNIQUE (token);


--
-- TOC entry 4720 (class 2606 OID 58021)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4723 (class 2606 OID 58041)
-- Name: events_registrations fk26hmjlwbxlogaf4xsh0oer40v; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events_registrations
    ADD CONSTRAINT fk26hmjlwbxlogaf4xsh0oer40v FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 4724 (class 2606 OID 58036)
-- Name: events_registrations fkjpt0w6f02llqp3ur4v4uiy53w; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events_registrations
    ADD CONSTRAINT fkjpt0w6f02llqp3ur4v4uiy53w FOREIGN KEY (event_id) REFERENCES public.event(id);


--
-- TOC entry 4722 (class 2606 OID 58031)
-- Name: event fklelt1nheas1gmn9t0nmc37a89; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event
    ADD CONSTRAINT fklelt1nheas1gmn9t0nmc37a89 FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- TOC entry 4721 (class 2606 OID 58026)
-- Name: activation_token fkpc3rhmxhs48sh9skcv8o9g7at; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activation_token
    ADD CONSTRAINT fkpc3rhmxhs48sh9skcv8o9g7at FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 4876 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


-- Completed on 2025-03-28 16:30:20

--
-- PostgreSQL database dump complete
--

